// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqdppexlhwukgnknpxdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZHBwZXhsaHd1a2dua25weGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjA3NTAsImV4cCI6MjA3MDIzNjc1MH0.QdsLmFkDoJxfgxrp1ZmTNtgWFuxYfbtqTbwf2mXytWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});